package com.xgh.model.query.enumerators;

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "enumerator")
public final class Enumerator {
    @Id
    private UUID id;

    private String kind;

    private String name;

    @Column(name = "auto_generated")
    private Boolean autoGenerated;

    @JsonIgnore
    private Boolean deleted = false;

    public Enumerator() {
    }

    public Enumerator(UUID id, String kind, String name, Boolean autoGenerated, Boolean deleted) {
        this.id = id;
        this.kind = kind;
        this.name = name;
        this.autoGenerated = autoGenerated;
        this.deleted = deleted;
    }

    public UUID getId() {
        return id;
    }

    public String getKind() {
        return kind;
    }

    public String getName() {
        return name;
    }

    public Boolean getAutoGenerated() {
        return autoGenerated;
    }

    public Boolean isDeleted() {
        return deleted;
    }

}
